<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit014d05ceffe5ee3ed256c3dcc0bede5d
{
    public static $prefixesPsr0 = array (
        'P' => 
        array (
            'PayPal' => 
            array (
                0 => __DIR__ . '/..' . '/paypal/rest-api-sdk-php/lib',
            ),
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixesPsr0 = ComposerStaticInit014d05ceffe5ee3ed256c3dcc0bede5d::$prefixesPsr0;

        }, null, ClassLoader::class);
    }
}
